<a href="https://colab.research.google.com/github/kamalavarshini15/kamalavarshini15/blob/main/day_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
L = [1,2,3,4,5,6,7]
type(L)

list

In [ ]:
a = np.array(L)

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
print(a)

[1 2 3 4 5 6 7]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape #gives tuple as answer

(7,)

In [ ]:
len(a.shape)

1

In [ ]:
print(a[6])

7


In [ ]:
a[0] = 9 # we can chnage element so it is mutable
print(a)

[9 2 3 4 5 6 7]


In [ ]:
L1 = [ [1,2,3],[4,5,6]]

In [ ]:
type(L1)

list

In [ ]:
b = np.array(L1)
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.shape #(dimension, no of values it has)

(2, 3)

In [ ]:
b[1].shape #(no of values,)(usually has one dimension )

(3,)

In [ ]:
b[0][1]

2

In [ ]:
type(b[0][1])
# it is a scalar value

numpy.int64

In [ ]:
a = np.zeros((5,3))

print(a) # data type is float by default

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a = np.zeros((5,3) , dtype =int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
c = np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#creates array with supplied elements

In [ ]:
c = np.full((3,2), 7)
print(c)

[[7 7]
 [7 7]
 [7 7]]


In [ ]:
d = np.eye(5, dtype=int) # eye is used for identity matrix
print(d)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
e = np.random.random((2,2))
print(e)

[[0.88635874 0.7364974 ]
 [0.36395626 0.74856696]]


In [ ]:
import numpy as np

a = np.array(([1,2,3,4] , [5,6,7,8], [9,10,11,12]))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a[1:3, 0:2]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
row_r1 = a[1, :3]

In [ ]:
row_r1

array([5, 6, 7])

In [ ]:
row_r1.shape

(3,)

In [ ]:
a[1:2 , :]

array([[5, 6, 7, 8]])

In [ ]:
a[[1,2], :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
c = np.array([0,2,0,1,2])
print(c)

[0 2 0 1 2]


In [ ]:
print(b[:,c])

[[ 1  3  1  2  3]
 [ 4  6  4  5  6]
 [ 7  9  7  8  9]
 [10 12 10 11 12]]


In [ ]:
# like range in loops in array we have 'arange'

In [ ]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [ ]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a > 2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [ ]:
a[a>2]

array([3, 4, 5, 6])

In [ ]:
print(a[a<4])

[1 2 3]


In [ ]:
x = np.array([1,2]) # we change the data types with hekp of dtype
y = np.array([1.0, 2.0])
z = np.array([1,2], dtype=np.float32)
print(x.dtype)
print(y.dtype)
print(z.dtype)

int64
float64
float32


In [ ]:
# in list it inly concatinates a list but not add elemnt inside the list
#so we use array

In [ ]:
L3 = []
L1 = [7,9,15]
L2 = [5,1,77]
for i in range (len(L1)):
  L3.append(L1[i] + L2[i])
print(L3)

[12, 10, 92]


In [ ]:
# to reduce the steps we can use list comprehension
[L1[i] + L2[i] for i in range(len(L1))]

[12, 10, 92]

In [ ]:
a = np.array([[1,2],[3,4]] , dtype = np.float64)
b = np.array([[5,6],[7,8]] , dtype = np.float64)


In [ ]:
a

array([[1., 2.],
       [3., 4.]])

In [ ]:
b

array([[5., 6.],
       [7., 8.]])

In [ ]:
(a+b)

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
np.add(a,b) # for substract

array([[ 6.,  8.],
       [10., 12.]])

In [ ]:
# noraml element multiplication and division

In [ ]:
print(np.sqrt(b))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [ ]:
x = np.array([[1,2],[3,4]], dtype = int)
y = np.array([[5,6],[7,8]])

z = np.array([9,10])
w = np.array([11,12])
print(z.shape,w.shape)


(2,) (2,)


In [ ]:
print(x.dot(y))
print(np.dot(x,y)) # it is the matrix multiplication

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
x @ y # 2 is the dot product

array([[19, 22],
       [43, 50]])

In [ ]:
n =  np.eye(2)
m = (np.dot(x,n))
print(m)

[[1. 2.]
 [3. 4.]]


In [ ]:
# it also has sum function which sums up all the values
k = np.array([[11,22],[33,44]])
print(np.sum(k))


110


In [ ]:
# to add column and row elements
print("Column wise sum : \n", np.sum(a,axis = 0))
print("row wise sum : \n", np.sum(a,axis = 1))

Column wise sum : 
 [4. 6.]
row wise sum : 
 [3. 7.]


In [ ]:
# for transpose we arrayy . T
print("Transpose\n", x.T)

Transpose
 [[1 3]
 [2 4]]


In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,10,11],[14,56,77]])
y = np.array([1,0,1])
z = np.empty_like(x) # create an empty array like x
print(x,y,z, sep="\n\n")

[[ 1  2  3]
 [ 4  5  6]
 [ 7 10 11]
 [14 56 77]]

[1 0 1]

[[ 1  2  3]
 [ 4  5  6]
 [ 7 10 11]
 [14 56 77]]


In [ ]:
for i in range(4): # long steps so as DS we need easy pacakge to perform this
  z[i,:] = x[i,:] + y
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8 10 12]
 [15 56 78]]


In [ ]:
for i in range(4):
  print(x[i,:])

[1 2 3]
[4 5 6]
[ 7 10 11]
[14 56 77]


In [ ]:
t = np.tile(y,(4,1)) # by this we can simply create the stack and add to required array instaed of using for loop to add the two arrays
print(t)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
s = np.add(x,t)
print(s)

[[ 2  2  4]
 [ 5  5  7]
 [ 8 10 12]
 [15 56 78]]
